# Generated by Django 4.0.6 on 2022-09-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siteData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('main_image', models.CharField(max_length=300)),
                ('discription', models.CharField(max_length=300)),
                ('attributes', models.CharField(max_length=300)),
                ('photos', models.CharField(max_length=1000)),
                ('price', models.CharField(max_length=80)),
                ('avalability', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
