# Generated by Django 4.0.6 on 2022-09-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='siteData',
            new_name='ProductData',
        ),
    ]
