# Generated by Django 4.0.6 on 2022-09-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_productdata_avalability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='avalability',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
