# Generated by Django 4.0.6 on 2022-09-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productdata_avalability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='attributes',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='productdata',
            name='discription',
            field=models.CharField(max_length=1000),
        ),
    ]
